<?php
namespace Home\Controller;


class BlackController extends CommonController {
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index(){
        //ºÚÃûµ¥
        $session_user = session("web_user");
        $uid = $session_user['user_id'];
        $where['uid'] = $uid;

        $info = M('dangeruser') -> where($where) -> select();

        $this->assign('info', $info);
        $this->display();
	}

}