<?php
namespace Home\Controller;


class BorrowController extends CommonController {
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index(){
        $show = i('show');
        $show = intval($show);
        //个人借出记录
        $uid = getUidFromSession();
        $gid = getGidFromSession();

        if($show == 0){
            $where['b_uid'] = $uid;
        }else{
            $where['gid']   = $gid;
        }
        $count = M('borrow') ->where($where)->count();
        $p     = new \Think\Page($count,20);
        $page  = $p->show();
        $info  = M('borrow') ->where($where)->order('id desc')->limit($p->firstRow.','.$p->listRows)->select();

        $userM = M('user');
        $usergM = M('user_group');
        foreach($info as &$v){
            $v['b_name']    = $userM -> where(['id' => $v['b_uid']]) ->getField('user_name');
            $v['group_name']= $usergM -> where(['id' => $v['gid']]) ->getField('group_name');
            $v['user_name'] =  $userM -> where(['id' => $v['uid']]) ->getField('user_name');
        }

        $this->assign('info', $info);
        $this->assign('show', $show);
        $this->assign('page', $page);
        $this->display();
	}

	public function addBorrow1(){
        $cate = M('category') -> where(array('is_delete' => 0, 'pid' => 0)) -> select();
        $userGroup = M('user_group')->where('is_delete=0')->select();
        $this->assign('cate', $cate);
        $this->assign('userGroup', $userGroup);
        $this->display();
    }

    public function addBorrow2(){
        $cat_id1 = i('cat_id1');
        $cat_id2 = i('cat_id2');
        $gid = i('gid');
        if(empty($cat_id1) || empty($cat_id2) || empty($gid)){
            $this->error('参数有误!');
        }
        $where['gid'] = $gid;
        $where['cat_id1'] = $cat_id1;
        $where['cat_id2'] = $cat_id2;
        $count = M('kucun') ->where($where)->count();
        $p     = new \Think\Page($count,20);
        $page  = $p->show();
        $info  = M('kucun') ->where($where)->order('id desc')->limit($p->firstRow.','.$p->listRows)->select();
        foreach ($info as &$val){
            $val['h_name'] = M('huoyuan')->where("id={$val['huo_id']}")->getField('h_name');
        }
        $this->assign('cat_id1', $cat_id1);
        $this->assign('cat_id2', $cat_id2);
        $this->assign('gid', $gid);
        $this->assign('page', $page);
        $this->assign('info', $info);
        $this->display();
    }

    public function addBorrow3(){
        $cu_id = i('cu_id');
        $cu_id = intval($cu_id);
        $huoInfo = M('kucun')->find($cu_id);
        $huoInfo['h_name'] = M('huoyuan')->where("id={$huoInfo['huo_id']}")->getField('h_name');
        $this->assign('huoInfo', $huoInfo);
        $this->assign('cu_id', $cu_id);
        $this->display();
    }

    public function doAdd(){
        $cu_id = i('cu_id');
        $info  = i('info');
        if(empty($cu_id)){
            $this->error('参数有误!');
        }

        $userInfo = session('web_user');
        $data['b_uid'] = $userInfo['id'];
        $data['b_mobile'] = $userInfo['mobile'];

        $cuInfo = M('kucun')->find($cu_id);
        if($cuInfo['num'] == 0){
            $this->error('已无库存');
        }
        $data['cu_id'] = $cu_id;
        $data['uid'] = $cuInfo['uid'];
        $data['gid'] = $cuInfo['gid'];
        $data['cat_id1'] = $cuInfo['cat_id1'];
        $data['cat_id2'] = $cuInfo['cat_id2'];
        $data['pic'] = $cuInfo['pic'];
        $data['info'] = $info;
        $data['c_date'] = time();
        $data['h_date'] = time()+3600*24*3;
        $res = M('borrow')->add($data);
        if($res){
            //库存减掉1
            $kuData['num'] = $cuInfo['num'] -1;
            M('kucun')->swhere("id={$cu_id}")->ave($kuData);
            $this->success('已经借出成功!');
        }else{
            $this->success('系统开小差了!');
        }

    }
}