<?php
namespace Home\Controller;


class BorrowController extends CommonController {
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index(){

        $this->display();
	}

}