<?php
namespace Home\Controller;


class CenterController extends CommonController {
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){


        $this->display();
	}

}