<?php
namespace Home\Controller;


class KucunController extends CommonController {
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index(){

        $session_user = session("web_user");
        $gid = $session_user['gid'];
        $where['gid'] = $gid;
        $info = M('kucun') -> where($where) ->select();

        foreach($info as &$v){

            $v['huoyuan_name'] =  M('huoyuan') -> where(['id' => $v['huo_id']]) ->getField('h_name');;

        }

        $this->assign('info', $info);

        $this->display();
	}

}