<?php
namespace Home\Controller;


class MemberController extends CommonController {
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //小组成员
    public function index(){
        $session_user = session("web_user");
        $gid = $session_user['gid'];
        $where['gid'] = $gid;
        $info = M('user') -> where($where)->order('level desc')->select();

        $this->assign('info', $info);
        $this->assign('session_user', $session_user);
        $this->display();
	}

	public function addMember(){
        $this->display();
    }

    public function address(){
        $this->display();
    }

}