<?php
namespace Home\Controller;


class MemberController extends CommonController {
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //小组成员
    public function index(){
        $session_user = session("web_user");
        $gid = $session_user['gid'];
        $where['gid'] = $gid;
        $where['id'] = array('NEQ', $session_user['user_id']);
        $info = M('user') -> where($where) ->select();

        $this->assign('info', $info);
        $this->display();
	}

}