<?php
namespace Home\Controller;


class MoneyController extends CommonController {
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index(){

        $status = I('status') ? I('status') : 0;
        $where['gid'] = getGidFromSession();

        if(1 == $status){
            $count = M('recharge') ->where($where)->count();
            $p     = new \Think\Page($count,4);
            $page  = $p->show();
            $info  = M('recharge') ->where($where)->order('id desc')->limit($p->firstRow.','.$p->listRows)->select();

            foreach($info as &$v){

                $v['c_date'] = date('Y-m-d H:i:s', $v['c_date']);
                if ( 1 == $v['state']) {
                    $v['status'] = '审核通过';
                } else if (0 == $v['state']) {
                    $v['status'] = '<font color="green">等待审核</font>';
                } else {
                    $v['status'] = '<font color="red">审核失败</font>';
                }
                $v['user_name'] = M('user')->where("id={$v['uid']}")->getField('user_name');
                //凭证有多张
                $pic  = explode(',',$v['pic']);
                $v['pic'] = $pic;
            }

        } else if(0 == $status) {
            $page = '';
            //账单表
            $info = M('bill') -> where($where) -> select();

            foreach($info as &$v){
                $v['c_date'] = date('Y-m-d H:i:s', $v['c_date']);
                $v['shop_name'] =  M('user_shop') -> where(['id' => $v['uid']]) ->getField('shop_name');
                if ( 1 == $v['state']) {
                    $v['state'] = '发货';
                } else {
                    $v['state'] = '调货';
                }
            }

        } else {
            echo '未知错误';exit;
        }

        $this->assign('status', $status);
        $this->assign('info', $info);
        $this->assign('page', $page);
        $this->display();
	}

}