<?php
namespace Home\Controller;


class ShopController extends CommonController {
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index(){

        $session_user = session("web_user");
        $gid = $session_user['gid'];
        $where['gid'] = $gid;
        $info = M('user_shop') -> where($where)->order('is_forbid asc ,id desc') ->select();

        $this->assign('info', $info);
        $this->display();
	}

    public function addShop(){
        $id = intval(i('id'));
        $info = M('user_shop')->find($id);
        if(IS_POST){
            $data = i('post.');
            unset($data['id']);
            $data['uid'] = getUidFromSession();
            $data['gid'] = getGidFromSession();
            $data['c_date'] = time();
            if(empty($data['shop_name']) || empty($data['shop_zg'])){
                $this->error('店铺名不为空');
            }
            if(empty($id)){
                M('user_shop')->add($data);
            }else{
                M('user_shop')->where("id={$id}")->save($data);
            }
            $this->success('操作成功');
        }else{
            $this->assign('info',$info);
            $this->display();
        }
    }


}