<?php
namespace Home\Controller;


class ShopController extends CommonController {
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index(){

        $session_user = session("web_user");
        $gid = $session_user['gid'];
        $where['gid'] = $gid;
        $where['is_delete'] = 0;
        $info = M('user_shop') -> where($where) ->select();

        $this->assign('info', $info);
        $this->display();
	}

}